services:
  pdb:
    image: postgres:16
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../skjera-docker.tmp:/var/lib/postgresql/data

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.116.1
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the Collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    env_file:
      - .env
