openapi: 3.1.0
info:
  title: Skjera Api
  description: Scienta's internal API for figuring out what's shakin'!
  version: 1.0.0

paths:
  /:
    get:
      tags:
        - skjera
      operationId: HelloWorld
      responses:
        200:
          description: Hello World
          content:
            text/plain:
              schema: { }

  /employee:
    get:
      tags:
        - skjera
      operationId: ListEmployees
      responses:
        200:
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"


  /meta/healthz:
    get:
      tags:
        - meta
      summary: ""
      operationId: MetaHealthz
      responses:
        200:
          description: Healthy
        503:
          description: Unhealthy

components:
  schemas:
    Employee:
      type: object
      required:
        - email
        - name
        - someAccounts
      properties:
        name:
          type: string
        email:
          type: string
        nick:
          type: string
        someAccounts:
          type: array
          items:
            $ref: "#/components/schemas/SomeAccount"

    SomeAccount:
      type: object
      required:
        - id
        - network
        - url
        - nick
      properties:
        id:
          type: integer
          format: int64
        network:
          type: string
        url:
          type: string
        nick:
          type: string

    SomeNetwork:
      type: string
      enum:
        - Twitter
        - LinkedIn
        - Slack
        - GitHub
        - GitLab
