[package]
name = "skjera"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
async-trait = "0.1.83"
axum = "0.7"
axum-extra = { version = "0.9", features = ["cookie", "multipart"] }
skjera_api = {version = "1.0.0", path="../skjera_api"}
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite", "postgres"] }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
