name: Build

on:
  push:
#    branches:
#      - main

env:
  REGISTRY: ghcr.io
  DATABASE_URL: postgres://skjera-owner:skjera-owner@localhost/skjera
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          [[ -x $(which sqlx) ]] || cargo install sqlx-cli

      - uses: actions/checkout@v4

      - shell: bash
        run: |
          # apt update
          # apt install --no-install-recommends --yes postgresql-client
          psql -f init.sql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          PGHOST: localhost

      - shell: bash
        run: |
          sqlx migrate run
          cargo sqlx prepare --workspace
          
          find .sqlx

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
